services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    ports:
      - "3901:3001"
    volumes:
      - ../backend:/app
      - /app/node_modules

  redis:
