services:
  api:
    user: "999:999"
    environment:
      - NODE_ENV=production
      - CLOUDFRONT_SECRET=${CLOUDFRONT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173}
      - LOG_LEVEL=info
    ports:
      - "3301:3001"
    restart: unless-stopped
    command: npm run start
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    user: "999:999"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
